# Generated by Django 5.1.4 on 2024-12-31 14:15

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import markdownx.models
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridSquare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=27700)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddb_id', models.CharField(max_length=20, unique=True)),
                ('taxon_name', models.TextField()),
                ('common_name', models.TextField()),
                ('tyk', models.CharField(max_length=16)),
                ('rank', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['taxon_name'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(editable=False)),
                ('body', markdownx.models.MarkdownxField()),
                ('publish_date', models.DateField()),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('grid_square', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='plantblog.gridsquare')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='plantblog.species')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', markdownx.models.MarkdownxField(max_length=500)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='plantblog.entry')),
            ],
            options={
                'ordering': ['entry', '-publish_date'],
            },
        ),
    ]
