# Generated by Django 5.1.4 on 2025-01-06 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['taxon_name'], 'verbose_name_plural': 'species'},
        ),
    ]
