# Generated by Django 5.1.4 on 2025-01-12 18:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantblog', '0002_alter_species_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-day_number'], 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterField(
            model_name='gridsquare',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
