# Generated by Django 5.1.4 on 2025-01-19 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantblog', '0003_alter_entry_options_alter_gridsquare_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='plantblog.species'),
        ),
    ]
