# Generated by Django 5.1.4 on 2025-01-19 19:55

import datetime
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GridSquare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=27700)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/% Y/% m/% d/')),
                ('caption', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddb_id', models.CharField(max_length=20, unique=True)),
                ('taxon_name', models.TextField()),
                ('common_name', models.TextField(null=True)),
                ('tyk', models.CharField(max_length=16)),
                ('rank', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'species',
                'ordering': ['taxon_name'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_data', models.DateField(default=datetime.date(2025, 1, 19))),
                ('sensitive', models.BooleanField(default=False)),
                ('abundance', models.SmallIntegerField(choices=[(1, 'Individual'), (2, 'Few'), (3, 'Many')], default=1)),
                ('location', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('osgrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='records.gridsquare')),
                ('photos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='records.photo')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='records.species')),
            ],
        ),
    ]
